### ISSUE TITLE
Feedback System

### ISSUE THREAD

**Issue by andrewmeme** [AncientMeme/procrastination#1]
# Description #
The prototype includes a feedback system where users can comment on other group members' journal submission. Once the comment gets a certain amount of upvotes, it would add land to the learning map for the user.

# Component #
* Mock journal pages created by other users
* A mock comment submission where the user can enter the feedback
* A timer where the user periodically gets more upvotes

# Dependency #
This feature is dependent on Learning Map

# Milestones #
* [x] Create a template page for a journal submission
* [ ] Fill in mock content
* [x] Keep track of the user comment submission
* [x] Adding value to the land counter
