### ISSUE TITLE
Journal Submission

### ISSUE THREAD

**Issue by SamSamRabbit** [AncientMeme/procrastination#2]
# **Description** #
The user submits her journal that will be shown on the home page.

# **Component** #
Home page
Journal submission page

# **Dependency** #
Journal submission page depends on the home page.

# **Milestones** #
- [x] Build a home page.

- [x] Build a journal submission page.

- [x] Create a button on the home page that connects to the journal submission page.

- [ ] The submission journal shows on the home page.
