### ISSUE TITLE
Map Page

### ISSUE THREAD

**Issue by Edwinxyzhu1999** [AncientMeme/procrastination#3]
# **Description** #
The user can open the map page and see their progress on it.

# **Component** #
Home page
Map page

# **Dependency** #
The home page has the map part on it

# **Milestones** #
- [ ] Build the home page.

- [ ] Build the map page.

- [ ] Create the map images (3 or 4).

- [ ] Leaderboard on who has the most land.
